GSG-G8/p2p-money

README.md
- For Client 
- For Admin
- As an Client 
- As an Admin
- FrontEnd 
- BackEnd 
- Database
- Team Lead
- Team members
#2
=>  added ReadMe file

client/package-lock.json, client/package.json, package-lock.json, package.json
- added backEnd modules and helper scripts
- added modules in frontEnd and added proxy 5000
#30
=> install frontEnd and backEnd modules

.vscode/settings.json
relates #9
added our team settings to vs code 
```js
{
"editor.formatOnSave": false,
"editor.tabSize": 2,
"editor.codeActionsOnSave": {
"source.fixAll": true,
"prettier.singleQuote": true,
},
}
```
=> add vs code settings and configuration

.travis.yml
=> create travis setup file

.eslintrc.js, client/.eslintrc.js, client/package-lock.json, client/package.json, package-lock.json, package.json
- added eslint for client and server 
- added prettier for client and server
#8
=> installed eslint and configration

client/.env, client/package-lock.json, client/public/index.html, client/src/components/App/index.js, client/src/index.js, package-lock.json, package.json
- fix build React error 
- add database structure for MongoDB.
=> fix build error & database structure

README.md
- added new database schema 
- replace MongoDB instead of PostgreSQL
=> added new database schema  and replace MongoDB instead of postgresql

server/database/models/transactions.js
=>  create transactions model

README.md
relates #63
- added schema to README file.
=> added schema image to README

server/app.js, server/controllers/routes/client/getClientData.js, server/controllers/routes/client/getClintData.js, server/controllers/routes/client/index.js, server/router/client.js, server/router/index.js
- create client controllers folder
- create client get all data function
- response all client data if the client exist
- response error message if not
- add a route in router index and import client router file
- create client router file
Relate #19
=> Create Get Client Controller

server/controllers/middlewares/index.js, server/router/index.js
- added middleWare to check client and send client id.
- added isClient to client route.
#24
=> isClient middleware

server/controllers/middlewares/index.js
-  added admin middleware to get admin id from cookies
#26
=> admin middleware

server/controllers/routes/client/index.js, server/controllers/routes/client/updateClient.js, server/router/client.js, server/utils/validations/updateClientValidation.js
[ ]- create update controller function
[ ]- create update validations
[ ]- create new update route
[ ]- handle change password
Relate #21
=> Update Client Data [CLIENT]

server/controllers/routes/client/addNewBank.js, server/controllers/routes/client/index.js, server/router/client.js, server/utils/validations/addBankValidation.js
- create add new bank function
- check body validation
- check if account number exists
- add new account number in bank account array
- response success or failed as process.
#68
=> Post New Bank account for user

server/controllers/routes/client/deleteBankAccount.js, server/controllers/routes/client/index.js, server/router/client.js, server/utils/validations/deleteBankValidation.js
- check if bank account exist
- check body validation
- response with message with status
Relate #69
=> Delete Bank Account [Client]

__test__/routes/logout.test.js, server/controllers/auth/logout.js, server/router/auth-router.js, server/router/index.js
- added logout route in back End in auth file 
- added test to admin and client logout
#16
=> logout Back-End

server/controllers/errors/clientError.js, server/controllers/errors/index.js, server/controllers/errors/serverError.js, server/database/dbConnection.js, server/router/index.js
- added server Error with route `/500`
- added client Error with route `/404`
- solved test problem with Travis
#84
=> Error handler

__test__/routes/getTransactions.test.js, server/controllers/routes/admin/getTransactions.js, server/controllers/routes/admin/index.js, server/router/admin.js
- create endpoint admin/transactions
- create a function to get all transactions from the database
- create a loop that get full name from id and get the detail of exchange transaction from the collection in the database
- response with status 200 and the array that have all information
- response with an error message if not.
Relate #6
=> Get Clients Transactions [Admin]

client/src/components/Common/Alert/index.js
- import alert ant design
- use config provider for arabic language
- create prop types
- export the function component
Relate #90
=> Alert Message Common Component

client/src/components/Common/Footer/index.js, client/src/components/Common/Footer/style.css
=> create footer component

client/src/components/Common/TextInput/index.js, client/src/components/Common/TextInput/style.css
relates #121 
- changed CSS file to style.css
- changed pixel to rem
- changed onchnge to is required
=> fixed css pixel naming and file

client/src/components/Common/Button/index.js, client/src/components/Common/Button/style.css
=> create common button component

client/package-lock.json, client/package.json, client/src/components/App/index.js, client/src/components/pages/admin/dashboard/index.js, client/src/components/pages/client/Bank/index.js, client/src/components/pages/client/Setting/index.js, client/src/components/pages/client/Signup/index.js, client/src/components/pages/client/Wallet/index.js, client/src/components/pages/common/Error404/index.js, client/src/components/pages/common/Home/index.js, client/src/components/pages/common/Login/index.js, client/src/index.js
- check if Admin, then get clients data and Transactions for Clients and give it to `/dashboard` route.
- check if Client, then get Client data, and give their data to `/wallet` route.
- added all pages folders and files.
#124
=> App routes

client/src/components/App/index.js, client/src/components/pages/common/Home/index.js, client/src/components/pages/common/Login/index.js, package.json
- edited Imported file name for Login and Home
- edited content Login and Home
=> Edits in App

server/controllers/auth/login.js
- fixed login error 
- the error cannot stop the server
=> Fixed login backend error

client/src/components/pages/client/Wallet/index.js, client/src/components/pages/client/Wallet/style.css
- added currency balance for each currency.
- fixed data passing
=> fixed wallet page

client/src/components/pages/client/Wallet/style.css
=> fixed wallet table styling

client/src/components/Common/selectBox/AdminSelect.js, client/src/components/admin/Chart/index.js, client/src/components/admin/Chart/queryReport.js, client/src/components/admin/Chart/style.css, client/src/components/pages/admin/dashboard/style.css, client/src/components/pages/client/Bank/index.js, client/src/components/pages/client/Bank/style.css, client/src/components/pages/client/Signup/firebase.js, client/src/components/pages/client/Signup/signUpForm.js, client/src/components/pages/common/Home/index.js, client/src/components/pages/common/Login/LoginForm.js
- fixed alert style
- fixed charts bug
- added new component select box and use it in admin page to specify data their want see  
- added events for buttons we need send data to google analytics
=> Fixed some problems

client/src/components/pages/admin/dashboard/style.css, client/src/components/pages/admin/dashboard/updatePrice.js
=> fix update prices direction
